name: yb_news
description: "YB News - Take Home Test Assessment"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Routing
  go_router: ^14.0.0

  # Network
  dio: ^5.4.0
  connectivity_plus: ^6.0.0

  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.4

  # Utils
  uuid: ^4.2.1
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0

  # UI
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.0
  google_fonts: ^6.1.0

  # Crypto
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
